import './globals.css'
import { AppProps } from 'next/app'
import { Inter } from 'next/font/google'
import { ClientProviders } from '@/lib/client-providers'
import { Thirdweb5Provider } from '@/lib/third-web/provider'
import { ThirdwebAutoConnect } from '@/lib/third-web/PagesAutoconnect'
import { AuthProvider } from '@/lib/auth-provider'
import useDetectDevice from '@/hooks/useDetectDevice'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Unicorn.eth',
  description:
    'Mobile View of Unicorn.eth Account Abstacrion Wallet generated by GM-Wallets',
}

export default function MyApp({ Component, pageProps }: AppProps) {
  const { isMobile } = useDetectDevice()

  return (
    <ClientProviders>
      <Thirdweb5Provider>
        <AuthProvider>
          <div className={inter.className}>
            <ThirdwebAutoConnect />
            <div className="fixed inset-0 m-auto flex max-w-[430px] flex-col items-center justify-center bg-white">
              {!isMobile ? (
                'This app can only be viewed on mobile.'
              ) : (
                <div className="flex w-full grow flex-col">
                  <div className="flex flex-col gap-10 px-[20px] py-20">
                    <Component />
                  </div>
                </div>
              )}
            </div>
          </div>
        </AuthProvider>
      </Thirdweb5Provider>
    </ClientProviders>
  )
}
