import { ClientProviders } from '@/lib/client-providers'
import './globals.css'
import { Inter } from 'next/font/google'
import { SafeAuthProvider } from '@/lib/safe-auth-provider'
import { headers } from 'next/headers'
import { Thirdweb5Provider } from '@/lib/third-web/provider'
import { ThirdwebAutoConnect } from '@/lib/third-web/AutoConnect'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Unicorn.eth',
  description:
    'Mobile View of Unicorn.eth Account Abstacrion Wallet generated by GM-Wallets',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const UA = headers().get('user-agent') || ''
  const isMobile = Boolean(
    UA.match(
      /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
    )
  )
  return (
    <ClientProviders>
      <Thirdweb5Provider>
        <SafeAuthProvider>
          <html lang="en">
            <body className={inter.className}>
              <ThirdwebAutoConnect/>
              <main className="m-auto flex min-h-screen max-w-[430px] flex-col items-center justify-center bg-white">
                {!isMobile
                  ? 'This app can only be viewed on mobile.'
                  : children}
              </main>
            </body>
          </html>
        </SafeAuthProvider>
      </Thirdweb5Provider>
    </ClientProviders>
  )
}
