import { ClientProviders } from '@/lib/client-providers'
import './globals.css'
import { Inter } from 'next/font/google'
import { SafeAuthProvider } from '@/lib/safe-auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClientProviders>
      <SafeAuthProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SafeAuthProvider>
    </ClientProviders>
  )
}
