import '@/app/globals.css'
import { ClientProviders } from '@/lib/client-providers'
import { Inter } from 'next/font/google'
import { Thirdweb5Provider } from '@/lib/third-web/provider'
import useDetectDevice from '@/hooks/useDetectDevice'
import { isBooleanObject } from 'util/types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Unicorn.eth',
  description:
    'Mobile View of Unicorn.eth Account Abstacrion Wallet generated by GM-Wallets',
}

const PagesLayout = ({ children }: { children: React.ReactNode }) => {
  const { isMobile } = useDetectDevice()
  if (typeof isMobile !== 'boolean') return
  return (
    <ClientProviders>
      <Thirdweb5Provider>
        <div className={inter.className}>
          <div className="fixed inset-0 m-auto flex max-w-[430px] flex-col items-center justify-center bg-white">
            {!isMobile ? 'This app can only be viewed on mobile.' : children}
          </div>
        </div>
      </Thirdweb5Provider>
    </ClientProviders>
  )
}

export default PagesLayout
