export const enum MODAL_TYPE {
  SETTINGS = 'SETTINGS',
  TRANSACTION = 'TRANSACTION',
  SEND = 'SEND',
  RECEIVE = 'RECEIVE',
  TOKEN_DETAIL = 'TOKEN_DETAIL',
  SETTINGS_GENERAL = 'SETTINGS_GENERAL',
  SETTINGS_CHANGE_CURRENCY = 'SECURITY_CHANGE_CURRENCY',
  SETTINGS_ACCOUNT_DETAILS = 'SETTINGS_ACCOUNT_DETAILS',
  SETTINGS_CHANGE_DOMIAN = 'SETTINGS_CHANGE_DOMIAN',
  SETTINGS_BUY_ENS = 'SETTINGS_BUY_ENS',
  COLLECTIBLE_DETAIL = 'COLLECTIBLE_DETAIL',
  CLAIM_DIGITAL_STICKER = 'CLAIM_DIGITAL_STICKER',
  WITHDRAW = 'WITHDRAW',
  SCAN = 'SCAN',
  DEPOSIT = 'DEPOSIT',
}

export const enum DEPOSIT_MODAL_TYPE {
  DEPOSIT = 'DEPOSIT',
  CHANGE_NETWORK = 'CHANGE_NETWORK',
}
